@startuml

class Lot {
    long id
    string name
    string description
    string pictureUrl
    datetime startDate
    datetime endDate
    decimal startPrice
    decimal currentPrice
    LotCategory category
    LotStatus status
    List<Tag> tags
}

class Tag {
    long id
    string name
    List<Lot> lots
}

class LotCategory {
    long id
    string name
    LotCategory? parent
}

enum LotStatus {
    ACTIVATED
    FINISHED
    DELETED
}

Lot - LotCategory
Lot - LotStatus
Lot - Tag

@enduml