@startuml

class Lot {
    Guid id
    string name
    string description
    string pictureUrl
    datetime startDate
    datetime endDate
    decimal startPrice
    Category category
    LotStatus status
    List<Tag> tags
}

class Tag {
    Guid id
    string name
    List<Lot> lots
}

class Category {
    Guid id
    string name
    Category? parent
}

class Bid {
    Guid id
    decimal bidValue
    datetime bidDate
    Lot bidUpLot
    Member member
}

class Member {
    Guid id
    string username
    decimal availableWallet
    decimal reservedWallet
    List<Bid> bids
    List<Lot> lots
}

enum LotStatus {
    ACTIVATED
    FINISHED
    DELETED
}

Lot - Tag
Lot - Category
Bid - Lot
Bid - Member
Member - Lot
Lot - LotStatus

@enduml