@startuml

class Lot {
    long id
    string name
    string description
    string pictureUrl
    datetime startDate
    datetime endDate
    decimal startPrice
    decimal currentPrice
    Category category
    LotStatus status
    List<Tag> tags
}

class Tag {
    long id
    string name
    List<Lot> lots
}

class Category {
    long id
    string name
    Category? parent
}

enum LotStatus {
    ACTIVATED
    FINISHED
    DELETED
}

Lot - Category
Lot - Tag
Lot - LotStatus

@enduml